name: my_FTP CI
on: [push]
jobs:
  compilation:
    name: Compilation via Makefile
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Compile with Make
      run: make re
    - name: Clean build
      run: make fclean

  tests:
    name: Unit tests and coverage
    runs-on: ubuntu-latest
    needs: compilation
    container:
      image: faurealexis/epitech-tools:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Compile tests
      run: make tests_run
    - name: Clean build
      run: make fclean

  test_commands:
    name: Test the number of commands implemented
    runs-on: ubuntu-latest
    needs: compilation
    container:
      image: faurealexis/epitech-tools:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Test commands
      run: docker compose up --build
    - name: Kill docker
      run: docker compose down

  push_to_epitech_repo:
    name: Push to Epitech repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@github.com:EpitechPromo2026/B-NWP-400-BDX-4-1-myftp-alexis.faure.git
        ssh_private_key:
          ${{ secrets.SSH_PRIVATE_KEY }}
